// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sem3_exam.Data;

#nullable disable

namespace Sem3_exam.Migrations
{
    [DbContext(typeof(TestDBcontext))]
    [Migration("20230922122413_SEM3_FinalTestMVC")]
    partial class SEM3_FinalTestMVC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sem3_exam.Mains.Models.TestJob", b =>
                {
                    b.Property<int>("department_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("department_code"));

                    b.Property<string>("department_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("number_of_personals")
                        .HasColumnType("int");

                    b.HasKey("department_code");

                    b.ToTable("Department_Tbl");
                });

            modelBuilder.Entity("Sem3_exam.Mains.Models.TestUser", b =>
                {
                    b.Property<int>("employee_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_code"));

                    b.Property<int>("department_code")
                        .HasColumnType("int");

                    b.Property<string>("employee_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_rnk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employee_code");

                    b.HasIndex("department_code");

                    b.ToTable("Employee_Tbl", (string)null);
                });

            modelBuilder.Entity("Sem3_exam.Mains.Models.TestUser", b =>
                {
                    b.HasOne("Sem3_exam.Mains.Models.TestJob", "TypeJob")
                        .WithMany()
                        .HasForeignKey("department_code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeJob");
                });
#pragma warning restore 612, 618
        }
    }
}
